language: android

jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.14
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

branches:
  only:
  - master
	
android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew clean :app:testDebugUnitTest :app:jacocoTestReport :app:coveralls

notifications:
email: false