language: android

jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.14
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository

script:
  bash gradlew test jacocoTestReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email: false